### ISSUE TITLE
Add `make rusttest`

### ISSUE THREAD

**Issue by wcampbell0x2a** [Rust-for-Linux/linux#248] opened 2021-05-02 23:37 UTC
I'm not sure how test harnessing works outside of using Cargo, and I know the `C kernel` relies on community testing. 

However, would there be a way of using the `mod tests` functionality that regular Rust users enjoy when testing kernel code?

**Comment by ojeda** [comment] 2021-05-02 23:48
We will have a way to do this, but it is not clear how it will exactly work just yet.

**Comment by ojeda** [comment] 2021-05-02 23:48
Closing since this is a duplicate of #40.

**Closed as completed by ojeda** 2021-05-02 23:48 UTC
Labels: • misc
