### ISSUE TITLE
No rust-analyzer suggestion in bindings

### ISSUE THREAD

**Issue by gipsyh** [Rust-for-Linux/linux#829] opened 2022-07-17 03:08 UTC
No rust-analyzer suggestion in bindings
<img width="626" alt="截屏2022-07-17 11 08 01" src="https://user-images.githubusercontent.com/42509521/179382136-b87a800d-92d7-4001-a118-87a151513b63.png">

<img width="507" alt="截屏2022-07-17 11 08 10" src="https://user-images.githubusercontent.com/42509521/179382139-59dd5d4c-10a5-4e4d-a002-6fa83c12abc8.png">

**Comment by bjorn3** [comment] 2022-07-17 12:40
Did you run `make rust-analyzer`, add `rust-project.json` to the `rust-analyzer.linkedProject` config and build linux or at least the rust directory to generate the bindings?

**Comment by gipsyh** [comment] 2022-07-17 12:46
> Did you run `make rust-analyzer`, add `rust-project.json` to the `rust-analyzer.linkedProject` config and build linux or at least the rust directory to generate the bindings?

yes
there is `binding_generated.rs` in `objtree/rust/bindings/`

rust-analyzer works fine except the `bindings suggestions`

**Comment by bjorn3** [comment] 2022-07-17 15:10
Did it work before https://github.com/Rust-for-Linux/linux/pull/822?

**Comment by tamird** [comment] 2024-10-28 20:00
I believe this is a dupe of #1050. In my recent experience rust-analyzer works with in-tree builds, but not out-of-tree builds. #1050 has more on that.

EDIT: wrong issue.

**Comment by ojeda** [comment] 2024-10-28 20:22
Sounds fine, thanks!

@gipsyh please feel free to reopen it is not the case (technically the other would be the duplicate -- I will add a note there to avoid forgetting Yuheng Su reported it)

**Closed as completed by ojeda** 2024-10-28 20:22 UTC
Labels: • kbuild
