### ISSUE TITLE
‘make LLVM=1 rustavailable’ wrong check on Fedora Linux 37 Server Edition Prerelease

### ISSUE THREAD

**Issue by qinirao** [Rust-for-Linux/linux#804] opened 2022-07-01 09:10 UTC
Hi, 
I test Rust on my Fedora Linux 37 Server, and get this:
```
# make LLVM=1 rustavailable
***
*** Rust bindings generator 'bindgen' is too new. This may or may not work.
***   Your version:     0.59.2
***   Expected version: 0.56.0
***
***
*** libclang (used by the Rust bindings generator 'bindgen') version does not match Clang's. This may be a problem.
***   libclang version: 13.0.1
13.0.1
***   Clang version:    13.0.1
***
Rust is available!
```
The libclang version is 13.0.1, but it shows
``` 
13.0.1
13.0.1
```
The problem is Fedora has a version number after clang version:
```
# bindgen ./scripts/rust-is-available-bindgen-libclang.h 2>&1 > /dev/null  | grep -F 'clang version '
./scripts/rust-is-available-bindgen-libclang.h:2:9: warning: clang version 13.0.1 (Fedora 13.0.1-1.fc37) [-W#pragma-messages], err: false
```
So, I think it may need a fix like this:
```
diff --git a/scripts/rust-is-available.sh b/scripts/rust-is-available.sh
index 6bd395167d0f..f05972a2e091 100755
--- a/scripts/rust-is-available.sh
+++ b/scripts/rust-is-available.sh
@@ -104,6 +104,7 @@ bindgen_libclang_version=$( \
        LC_ALL=C "$BINDGEN" $(dirname $0)/rust-is-available-bindgen-libclang.h 2>&1 >/dev/null \
                | grep -F 'clang version ' \
                | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' \
+               | head -1 \
 )
```
Thanks.

**Comment by bjorn3** [comment] 2022-07-01 09:12
The libclang error is https://github.com/Rust-for-Linux/linux/issues/777.

**Comment by nbdd0121** [comment] 2022-07-02 17:32
Yeah, it's a duplicate of #777

**Closed as not planned by nbdd0121** 2022-07-02 17:32 UTC
Labels: • kbuild
